[target.'cfg(target_os = "none")']
runner = "./qemu_wrapper.sh"

[unstable]
# cross compile core library for custom target
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "i686-os.json"
